README.md, jf_agent/bb_download.py, jf_agent/main.py, setup.py
Also fixes a bug with the --since handling; we were stopping pulling entirely as soon as we hit a single repo with a commit or PR before the since date instead of going on the next repo.  That is now fixed.
=> Allow redacting names and URLs

example.yml, jf_agent/git/__init__.py, jf_agent/git/bitbucket_cloud_adapter.py, jf_agent/git/gitlab_adapter.py, jf_agent/main.py
This adds a configuration option to filter on bitbucket cloud projects.
This is a bit messy, because we already have `include_projects` for git, which in the case of Bitbucket Cloud, maps to top-level organization to connect to.  And other providers don't have a perfectly analogous thing.
=> OJ-6775: Allow filtering on bitbucket cloud projects

jf_agent/git/github_client.py
Workaround for GitHub Cloud 403 error after rate limiting
=> [OJ-7002] Rate limiting hack

jf_agent/git/bitbucket_server.py
This error is arising for a user; print and log it, then move on instead of crashing.
=> OJ 8347 - catch additional error

Dockerfile, hooks/build, jf_agent/diagnostics.py
Allows for more detailed messaging to be logged by the Jellyfish API.
=> OJ-8692: Upload agent build timestamp to S3, along with SHA

jf_agent/jf_jira/jira_download.py
Catch and log 400 errors that occur when attempting to get project_boards without the right permissions
=> OJ-8911: Catch and log permission errors from trying to fetch project_board 

jf_agent/jf_jira/jira_download.py
The changelog from Jira Cloud can contain history for fields we are trying not to pull.  Explicitly filter those out.
=> OJ-8990: Jira API can sometimes send back extra data 

jf_agent/git/__init__.py
Use repos_dict_v2 instead of repos_dict in pull_since_date_for_repo; this is keyed by repo_id instead of by org_login-repo_id
=> OJ-8923: Use repos_dict_v2 instead of repos_dict in pull_since_date_for_repo

jf_agent/jf_jira/jira_download.py
Some changelog history items do not have `fieldId`, so use 'field` if available. Also include some additional safeguards.
=> [OJ-9084]: Jira changelog histories can get incorrectly omitted

jf_agent/git/gitlab_client.py
Removes some wonky error handling, remove unused `merge_request.approvers` variable. This seems to be something that happens in older versions of GitLab.
=> [OJ-9467] Handle situation where gitlab gives back bogus approvals

jf_agent/git/gitlab_adapter.py
Send back the author date for commits from gitlab.
=> [OJ-9479] Send `authored_date` back from GitLab API

jf_agent/git/__init__.py, jf_agent/git/bitbucket_cloud_adapter.py, jf_agent/git/bitbucket_server.py, jf_agent/git/github.py, jf_agent/git/github_client.py, jf_agent/git/gitlab_adapter.py, jf_agent/git/gitlab_client.py
This provides support to agent for collecting merge_commit data as a component of git data for Github, Gitlab and Bitbucket Cloud. This is inversely queried by JFGithubCommit.merged_pull_requests. Useful for tracking the commit on the base branch that a PR resulted in.
Bitbucket server does not support getting this information, but it is added here for github, gitlab, and bitbucket cloud. 
Tested with our Github, Gitlab and bitbucket cloud
=> OJ-9792: Changes to introduce merge_commits

jf_agent/git/bitbucket_cloud_adapter.py
With the recent change to include merge_commit data, I'd failed to account for the case where we receive no merge_commit data for Bitbucket Cloud. This resulted in PRs being dropped when the data was missing. This fixes that issue by setting merge_commit to None initially.
Local with Orthog bitbucket cloud
=> OJ-10070: Support bitbucket cloud PRs with no merge commit

jf_agent/agent_logging.py, jf_agent/config_file_reader.py, jf_agent/git/__init__.py, jf_agent/git/bitbucket_cloud_adapter.py, jf_agent/git/bitbucket_cloud_client.py, jf_agent/git/bitbucket_server.py, jf_agent/git/github.py, jf_agent/git/github_client.py, jf_agent/git/gitlab_adapter.py, jf_agent/git/gitlab_client.py, jf_agent/jf_jira/__init__.py, jf_agent/jf_jira/jira_download.py, jf_agent/main.py, jf_agent/ratelimit.py, jf_agent/session.py
To help start designing more Agent tooling, classify the errors in the Agent to understand what errors are often thrown and provide a small boost to organization of errors in our logs. 
This small boost means just adding a tag to each log that classifies what groups of people are best suited to "fix" the error or be aware of it. This means that when we see a CLIENT_CONFIG error in the logs, it's not engineering's job but the client's.
Ex: 
`2021-02-08 00:00:15 MainThread WARNING [3002] You do not have the required permissions in jira required to fetch boards for the project 123145`
Furthermore, added comments to classify non-logging statements to help with further designing to understand what may need to change and where those errors/prints/raises lie in the codebase.
=> [OJ-9533] - Classify errors in the agent

jf_agent/git/bitbucket_server.py
It seems this can throw either a `GenericException` or a `RetryError`, so catch both of them.
=> [OJ-10612] Catch `RetryError` when fetching bitbucket server comments

example.yml, jf_agent/config_file_reader.py, jf_agent/main.py
Include a new flag to `config.yml` called `send_agent_config` which will, if `True`, send the customers' config.yml file to the s3 bucket.
Set flag to `True` in `config.yml`:
```
daviskeene@Davis-Macbook-Pro:~$ aws s3 ls s3://jellyfish-dev-agent-upload/orthogonal-networks/20210603_183816/
2021-06-03 14:38:50          0 .done
2021-06-03 14:38:50        658 config.yml
2021-06-03 14:38:49        478 diagnostics.json.gz
2021-06-03 14:38:49       7849 jf_agent.log
2021-06-03 14:38:49        135 status.json.gz
```
Flag not included in `config.yml`:
```
daviskeene@Davis-Macbook-Pro:~/jf_agent$ aws s3 ls s3://jellyfish-dev-agent-upload/orthogonal-networks/20210603_184116/
2021-06-03 14:42:48          0 .done
2021-06-03 14:42:47        499 diagnostics.json.gz
2021-06-03 14:42:47       7847 …
```
=> OJ-10065: Add config option to send agent config information to Jellyfish

jf_agent/git/__init__.py, jf_agent/jf_jira/jira_download.py, jf_agent/main.py
Currently, the agent’s “validate” mode checks that the agent can contact Jira, that it can enumerate Jira users, and that it has access to the Jira projects it’s configured for. This PR adds the following functionality:
- Ability to reach the Git instance(s) configured
- ability to see the Git orgs/project(s) configured
Local agent "validate" mode runs
Agent output available upon request
=> OJ-9530: Add Git diagnostic information to agent "validate" mode

jf_agent/jf_jira/jira_download.py
When clients run their agent, sometimes there are comments on the output surrounding createmeta permissions. Most notably we display a 500 error in the traceback. While it's not necessarily an issue for the agent and doesn't stop it from running, for a client who isn't well aware of our Agent and pays attention to this, it can be concerning.
This PR removes the traceback and changes this error from an `Error` to a `Warning`.
None. Straightforward change.
N/A
=> OJ-9107: Enhance agent logging on `createmeta` permissions.

jf_agent/main.py
This PR refactors the `validate` run mode so that we can check for valid jira credentials and git configs before attempting to validate them.
Local agent runs using the `validate` run mode and different `config.yml` configurations.
=> OJ-11482: Run Jira and Git validation only if credentials / configuration exists

jf_agent/agent_logging.py, jf_agent/git/__init__.py, jf_agent/git/bitbucket_server.py
A customer is experiencing exceptionally long loading times when adding a new repository to their git configuration. This adds some extra diagnostic information (timestamps, pull_from date) when running bitbucket server in `verbose` mode.
=> [OJ-11721] Clean up, add verbose logging for bitbucket server

example.yml, jf_agent/git/__init__.py, jf_agent/git/bitbucket_cloud_adapter.py, jf_agent/git/bitbucket_server.py, jf_agent/git/github.py, jf_agent/git/gitlab_adapter.py, jf_agent/main.py, jf_agent/validation.py, tests/test_bitbucket_cloud_adapter.py, tests/test_github.py, tests/test_gitlab_adapter.py
When comparing repo names against include_repos/exclude_repos from the config file, use case INsensitive comparisons.
Also a few other small bug fixes, messaging tweaks, minor code re-org.
Have tested for all four providers.
=> OJ- 11977: Case insensitive comparisons for repo names

jf_agent/git/bitbucket_server.py
This try catch used to exist:
https://github.com/Jellyfish-AI/jf_agent/blob/471a4f12147005a792e830eb8abd03d1b2a51708/jf_agent/git/bitbucket_server.py#L171-L176
It was not ported over in a refactoring to facilitate pulling commits from non-default branches. Adding it back to avoid NotFoundExceptions in cases where the default branch of a repo can not be retrieved.
=> OJ-12746: Handle NotFoundException for default branch

jf_agent/jf_jira/jira_download.py
If we are using category-based include/exclude conditions, handle the
case where projects lack a defined category.
Tested locally via Jira Server Docker container.
=> [OJ-12964] Handle case where `projectCategory` is not set

example.yml, jf_agent/git/bitbucket_server.py, jf_agent/git/github.py, jf_agent/git/gitlab_adapter.py, jf_agent/git/utils.py
This adds the ability for users to use wildcard patterns when specifying the branches from which we should pull commits. 
Ran against Github and Gitlab implementations and verified that the expected branches were pulled when using wildcards
=> OJ-12951: Allow regex branch names in config

jf_agent/git/gitlab_adapter.py
Code in the the Gitlab Adapter was using the `.total` attribute of underlying python-gitlab objects
to determine whether to print a message when there were no MRs pulled from a repository.
It was also used in a call to `tqdm` to draw a fancy progress bar.
The implementation of this `.total` property in `python-gitlab` relies on parsing the `X-Total` HTTP header
from the GL API response. See https://github.com/python-gitlab/python-gitlab/blob/64d01ef23b1269b705350106d8ddc2962a780dce/gitlab/client.py#L1007
According to Gitlab's API reference, these heders are ommited for large repos, see: https://docs.gitlab.com/ee/user/gitlab_com/index.html#pagination-response-headers
In the end, this results in erroneusly skipping pulling the MRs from repositories that contain a large amount of MRs.
Since …
=> fix(git/gitlab_adapter): don't use the total attribute of python-gitab objects to enable pulling MRs from large repos

jf_agent/config_file_reader.py, jf_agent/git/gitlab_adapter.py
This patch adds an ability to recursively and implicitly include all repositories in a certain project when fetching data from Gitlab.
Use case: Let's say I have a main group A with 100 repositories and a subgroup B. My preferred usecase it to be able to pull data from 5 projects in group A and all projects in group B.
With the situation before this patch, I essentially had two options, either:
a) put 5 repos from group A and then X repos from subgroup B in `include_repos` git config section
b) put all _other_ repos that I'm not interested in `exclude_repos`
Both of those ways are quite suboptimal in a sense that they require a lot of manual list management.
That's why this patch introduces two new Git config parameters: `include_projects_recursively` and `exclude_projects_recursively`. …
=> feat(gitlab): Enable excluding and including repositories recursively on a group/project level

jf_agent/git/github.py
We noticed that, despite having configured `strip_text_content: True` for our GitHub organization, the pull request comments were still visible in the output files.  We traced it to what appears to have been an oversight, as the `bitbucket_server` implementation does sanitize PR comments.
Given:
1. a configuration file which contained (among others) a Git configuration pointing to one of our GitHub Cloud organizations, with `strip_text_content: True`
2. a custom-built container (leveraging the included `hooks/build` script) tagged as `jf_agent:kxs`
When:
I ran `docker run (...) jf_agent:kxs -m download_only`
Then:
1. The `bb_prs.json` file for the GitHub repositories had the values of the `body` key under `comments` contain either nothing or the agent's guess at JIRA issue keys.
Mission …
=> fix: sanitize GitHub PR comment bodies

README.md, example.yml
Rather than use the instance-wide `no_verify_ssl` switch, these changes document how to configure the agent to trust more certificates than those that came with the application.
Given:
1. a Bash script called `agent.sh` similar to the snippet in the `README.md`
2. a configuration file which contained `no_verify_ssl: False` and 2 Git configurations
3. a `cacert.pem` file which was augmented with some CA certificates our administrators are using to issue certificates for various services
When:
I ran `./agent.sh -m validate`
Then:
1. The first Git entry in our configuration file is our self-hosted Bitbucket server, which has a certificate issued by a custom CA certificate.  The connection was successful. (without these changes, this would fail to connect with the `CERTIFICATE_VERIFY_FAILED` …
=> doc: document the use of REQUESTS_CA_BUNDLE to work with custom certificates

.gitignore, example.yml, jf_agent/config_file_reader.py, jf_agent/jf_jira/__init__.py, jf_agent/jf_jira/jira_download.py
A potential customer has loaded many thousands of customer records (including PII) into their Jira Data; they wish to have a way to filter this data out of what is sent to Jellyfish.
This PR adds the following capabilities to our `config.yml`:
```
#
#
```
NOTE: the changes to `download_all_issue_metadata` are a side effect of formatting with `black, version 19.10b0`
=> OJ-18867 implement `jira.required_email_domains` config option

jf_agent/jf_jira/jira_download.py
Fixes a bug where the max length was not considering the extra characters from the escaped commas and extra params in the url.  This led to a situation where with just enough issue ids the issue ids would not get split and the url would be too long.
=> OJ-18952: Handle extra characters from escaped commas

jf_agent/jf_jira/jira_download.py
Needs to be a list so it can be split - comes in as a set.
=> OJ-18980: project_ids bug: Change project_ids to list

jf_agent/config_file_reader.py, jf_agent/git/github_client.py, jf_agent/main.py
This adds basic parallelization to git downloading, by git configuration. Each git config is subject to a different rate-limit so this should be a substantial speed performance for multi-git use-cases.
=> Parallelize git download by git configuration

jf_agent/validation.py
main checks for whether we use bearer or user/pass but `validate` only had a password path until now
=> OJ-21128: allow printing bearertoken masked

.pre-commit-config.yaml, Pipfile, Pipfile.lock, jf_agent/__init__.py, jf_agent/config_file_reader.py, jf_agent/git/__init__.py, jf_agent/git/bitbucket_cloud_adapter.py, jf_agent/git/bitbucket_server.py, jf_agent/git/github_client.py, jf_agent/git/gitlab_adapter.py, jf_agent/git/utils.py, jf_agent/jf_jira/jira_download.py, jf_agent/main.py, jf_agent/validation.py, tests/test_bitbucket_server.py, tests/test_gitlab_adapter.py
Add `black` formatting logic to the `jf_agent` repository, so that all code stays consistently formatted.
I opted to lock us into `black` version `19.10b0` to keep us in sync with other internal repositories. Locking us into that version required us to install a dependency on the `click` library, which I also locked into place to ensure we stay in sync with `black`. Additionally I need to install the `pre-commit` library. This is all contained within the python virtual env.
=> OJ-21409-add-pre-commit-formatting-rules

.github/workflows/snyk-monitor.yml
This PR adds a new GitHub Action for running `snyk monitor` on pushes to the master branch.
This will be used to gather third-party dependencies and upload to Jellyfish's Snyk account for tracking. This will bring this repo into operational parity with our other repos.
I verified this by temporarily adding an `on:` rule that fires the `snyk monitor` workflow on PR (i.e., this PR) and examined the output of: https://github.com/Jellyfish-AI/jf_agent/actions/runs/4283820506/jobs/7459917268
You'll see a snapshot was properly created and upload:
```
...
Explore this snapshot at https://app.snyk.io/org/jellyfish-k9n/project/8e2b4e4a-ea2f-4ffc-9ee1-7b50fda7e46c/history/a5dfc3b2-0580-4453-b3b4-57983c88349c
...
```
I've also created a new Snyk service account and generated an access token that has …
=> [OJ-21241] Add snyk monitor job to track vulns in dependencies

jf_agent/agent_logging.py, jf_agent/main.py
Some agent clients have been seeing issues when uploading files from their agent containers to S3. The specific issues have to do with `104 - Connection Reset` errors being thrown intermittently. This PR contains some retry logic to make our file uploads more robust
=> OJ-22785-add-104-retry-logic-to-file-upload

jf_agent/agent_logging.py, jf_agent/main.py
Improve logging when uploading files.
- Logging statement is made when a file is successful uploaded
- Logging message on retry logs with the error message in it's actual message
- If we fail to upload after all our retry attempts, log an error
=> OJ-22882-file-upload-logging-improvement

.github/workflows/secrets-detect.yml, .pre-commit-config.yaml, .secrets.baseline, README.md
This PR adds a new pre-commit hook and GitHub actions job to detect accidental inclusion of sensitive data (private keys, slack webhooks, etc.)
A "baseline" file is included which will prevent detect-secrets from reporting on findings in those data files in the future. I audited all those findings and they were not actual issues (they were git commit hashes).
**Testing:**
1. Commit and push change locally (when your change does not have any secrets included in it).
2. Note pre-commit does not flag any issues
3. Note CI passes cleanly
4. Now create fake change which includes a "suspicious" value. i.e. include `API_KEY = 'Test'` somewhere.
5. Commit and push
6. Note pre-commit fails
7. Push with `--no-verify` to skip pre-commit hooks
8. Note that CI Job fails.
**Screenshots:**
Example of …
=> [OJ-23618] Add precommit and CI job to detect secrets in PRs or commits

jf_agent/data_manifests/git/generator.py
There is a bug in manifest generation. This bug _generally_ only affects non-github instances, but it can snag some outliers.
=> OJ-24727-cleanup-git-generator-bug

jf_agent/data_manifests/jira/adapter.py, jf_agent/data_manifests/jira/generator.py, jf_agent/data_manifests/jira/manifest.py
Add Project Manifests to Jira Manifest Uploads
This code has been tested against my localhost of our Jellyfish API, and I have confirmed that we can successfully deserialize the uploaded manifest and that the deserialized manifest contains the proper values.
=> OJ-25748-jira-project-manifests

jf_agent/data_manifests/jira/adapter.py
Rework Jira Manifest project generation to work with both Jira Cloud and Jira Server. Instead of only using the `GET /rest/api/latest/project/search` endpoint, which is only available in Jira Cloud instances, we now leverage Jira Server's "get all projects" API endpoint (`GET /rest/api/latest/project`). This API endpoint is technically available in Jira Cloud as well but it is marked as depreciated. For that reason I have introduced an if statement that will conditionally use either API endpoints depending on if GDPR is active or not.
[Jira Cloud API docs](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-search-get)
[Jira Server API docs](https://docs.atlassian.com/software/jira/docs/api/REST/9.9.0/#api/2/project-getAllProjects)
For …
=> OJ-26192-cleanup-manifest-logging

jf_agent/data_manifests/jira/adapter.py, jf_agent/data_manifests/jira/generator.py, jf_agent/data_manifests/jira/manifest.py
Remove board_count from Jira Project Manifests. This field is no longer used internally
=> OJ-26362-cleanup-board-counts

jf_agent/agent_logging.py, jf_agent/jf_jira/jira_download.py
Log an error whenever we get a 400 back from the Jira sprints endpoint, rather than bombing out.
=> [OJ-26479] Log Error on Sprints 400

jf_agent/data_manifests/jira/adapter.py, jf_agent/data_manifests/jira/generator.py, jf_agent/data_manifests/jira/manifest.py
Remove sprint counts from agent uploads to expedite manifest generation
=> OJ-27251-remove-sprint-counts-from-manifests

jf_agent/data_manifests/jira/adapter.py
A trailing slash in Jira URLs doesn't play nicely with our manifest generator logic. This removes a trailing slash on the URL, if it present
=> OJ-27352-cleanup-jira-manifest-trailing-slash-bug-in-manifest-gen

jf_agent/data_manifests/git/adapters/github.py, jf_agent/data_manifests/git/generator.py
Re work base URL for graphql base Manifests, which should allow Github Enterprise Server clients to generate manifests
=> OJ-27539-re-work-gh-graphql-base-url-for-manifests

jf_agent/data_manifests/git/adapters/github.py
Experimentally adjust graphql endpoint URL. Re-checking the docs, it looks like I forgot the base `/api` before the `/graphql` part
=> OJ-27539-adjust-graphql-endpoint-in-manifests

jf_agent/data_manifests/git/adapters/github.py, jf_agent/data_manifests/git/adapters/manifest_adapter.py, jf_agent/data_manifests/git/generator.py, jf_agent/data_manifests/git/manifest.py
Reduce scope of GitDataManifest generation to not need `[read:org]`. This includes removing any reference to the `name` field when querying for a github `organization`, as well as removing the notion of `TeamManifests` from `GitDataManifests`
See OJ-27623 for internal side changes related to this PR
=> OJ-27619-reduce-scope-of-github-manifest-gen

jf_agent/data_manifests/git/adapters/github.py, jf_agent/data_manifests/manifest.py
GZIP compress all manifest uploads to make manifest uploading more efficient
=> OJ-27616-add-compression-to-manifest-uploading

jf_agent/data_manifests/git/adapters/github.py, jf_agent/git/__init__.py, jf_agent/git/github_gql_adapter.py, jf_agent/git/github_gql_client.py, jf_agent/git/github_gql_utils.py, jf_agent/git/gitlab_adapter.py, jf_agent/git/gitlab_client.py, jf_agent/git/utils.py, jf_agent/main.py
Introduce a new Github Adapter that leverages Graphql to greatly increase speed of data ingestion. The biggest gains here will be realized by speeding up our pull request ingesiton
See the related Jira Ticket for a more in-depth analysis of this change
=> OJ-27617-refactor-github-ingest-to-use-gql

jf_agent/git/github.py, jf_agent/git/github_gql_adapter.py, jf_agent/git/github_gql_client.py, jf_agent/git/utils.py
Clean up potential edge cases, notably around empty repositories not having default branches.
Additionally clean up null serialization to play nicer with our `git_import` logic
=> OJ-28319-gql-edge-case-cleanup

jf_agent/git/github_gql_utils.py
Add the `User-Agent` header to the Graphql Github Client. This should resolve some issues that clients are seeing when fetching Pull Requests. We are getting `403` errors that I believe have to do with WAF rules when pulling data, and setting this header may get us around those problems
=> OJ-28494-introduce-user-agent-header-to-gql-client

jf_agent/git/__init__.py, jf_agent/git/github_gql_adapter.py, jf_agent/git/github_gql_client.py, jf_agent/git/github_gql_utils.py
Some of our extra large clients, that also implement threading, are running into secondary rate limiting when running git ingest with GQL. To get around this, I added retry logic to the `GithubGraphqlClient` class
I also made an effort to reduce the total number of calls made per git ingest. See the `get_repos` function, and how we are now caching whether or not the repo (and it's default branch) should pull from the API again
- Move Graphql Client logic to `github_gql_client.py` and out of the `github_gql_utils.py` file
- Add in retry logic to the `GithubGqlAdapter.get_raw_result` function
- Reduce number of total API calls by caching the latest commit date and latest PR update time in memory
To test, I modified my local environment to call the `api.github.com/graphql` endpoint against …
=> OJ-28550: add retry logic and reduce total API calls

jf_agent/git/__init__.py, jf_agent/git/github_gql_adapter.py, jf_agent/git/github_gql_client.py, jf_agent/main.py
Disable 'Top Level' comments on reviews, akak 'IssueComments' vs 'PullRequestReviewComments' in the GQL schema
This is inline with how we are doing comments in the 'legacy' github ingest, and better reflects how comments are tracked by our metrics
=> OJ-28629-disable-top-level-comments-from-getting-pulled

jf_agent/git/github_gql_adapter.py, jf_agent/git/github_gql_client.py
This pull requests gets rid of the function that is used to determine the page size when pulling repos. This page size function was initially introduced to help us quickly see if there are no PRs that we need to pull, but it has since been replace by the `reop_has_quiescent_prs_lookup` look up table. Getting rid of this superfluous page size checking will help reduce our total number of calls and fly lower under the GQL API rate limiter
=> Oj 28632 reduce number of api calls for prs

.github/workflows/snyk-monitor.yml
This PR fixes up our Snyk CI so that we can monitor jf_agent dependencies for vulnerabilities following the switch to pdm.
Evidence monitor now works:
=> [OJ-28830] Fix snyk-monitor after change to pdm

jf_agent/__init__.py, jf_agent/agent_logging.py, jf_agent/config_file_reader.py, jf_agent/data_manifests/git/generator.py, jf_agent/data_manifests/jira/adapter.py, jf_agent/data_manifests/jira/generator.py, jf_agent/data_manifests/manifest.py, jf_agent/git/__init__.py, jf_agent/git/bitbucket_cloud_adapter.py, jf_agent/git/bitbucket_cloud_client.py, jf_agent/git/bitbucket_server.py, jf_agent/git/github.py, jf_agent/git/github_client.py, jf_agent/git/github_gql_adapter.py, jf_agent/git/github_gql_client.py, jf_agent/git/gitlab_adapter.py, jf_agent/git/gitlab_client.py, jf_agent/git/utils.py, jf_agent/jf_jira/__init__.py, jf_agent/jf_jira/jira_download.py, jf_agent/main.py, jf_agent/ratelimit.py, jf_agent/session.py, jf_agent/validation.py
Rework logging in the agent so we have a less specialized `agent_logging` class. To do this, I replaced a lot of the `log_and_print` calls with simple `logger.info` calls, and changed around the handlers in the `agent_logging.configure` function to leverage both a file emitter and an stdout emitter
To make refactoring simplier, I decided to leave in the `log_and_print_error_or_warning` function. This could probably get replaced with individual `logger.warn` and `logger.error` calls, but that is a tedious refactor that I am punting for now
---
The new pattern for logging is documented in the `agent_logging.py` file. The gist is this:
`print()` calls are still used for sensitive customer data, when we need to print to inform them about stuff. This is mainly used in `-m validation`, where we …
=> OJ-29421-normalize-agent-logging

jf_agent/main.py, pdm.lock, pyproject.toml
Working with JF Ingest locally and Agent is pretty burdensome, because you have to recreate the docker image everytime you change a dependency change (jf_ingest). To speed up dev time/quality of life, I think it makes sense to expose running the `main.py` function directly. You can already do this, but we're missing some vital logic to ingest your creds file. In this PR, I'm adding a dependency and program argument 
I have updated the proper documentation, showing you how to use this new command [here](https://jelly-ai.atlassian.net/wiki/spaces/JEL/pages/2963210264/Working+with+Jellyfish+Ingest#Working-with-JF-Ingest-in-Agent)
=> OJ-30027-add-agent-dev-mode

jf_agent/jf_jira/jira_download.py
For a new Agent client we are having trouble getting _all_ their user data. This is happening because the way we guess at what wildcard will work for a specific jira server involves checking against the potential wildcard `%` which **is not** a wildcard character in this particular customers Jira Server. Since `%` is such an uncommon character in a username/email we typically would find no results and move on to the next wild card to try. In this instnace, however, this is one singular user with a `%` character in their first name. When we attempt to grab all users, we end up only grabbing that user#285 
To resolve this, I introduced a `""` wild card search before the `%` search. According to curl examples provided by our client, this should fetch all of their users
=> OJ-30416-filter-by-empty-str-before-percent-sign

jf_agent/__init__.py, jf_agent/config_file_reader.py, jf_agent/exception.py, jf_agent/main.py, jf_agent/util.py, jf_agent/validation.py, pdm.lock, pyproject.toml
A few medium-sized changes to agent code:
- Cuts over the validation run mode to use the validate_function that has been moved into jf_ingest.
- Adds a helper function, `get_jira_ingest_config`, that will take in the agent config and credentials and output a JiraIngestionConfig as defined in jf_ingest.
- Moves around some logic, including the get_company_info call, which is now encapsulated in it's own function.
- Fixes an issue with validate_memory to use the config file's outdir rather than a hardcoded one.
This will make it easier for us to use the jf_ingest validation code and other parts of jf_ingest Jira code, and will help share this logic to aid debugging.
=> [OJ-30980] Move validate run mode to use jf_ingest validation methods

jf_agent/main.py
This is wrapped in a broad try except, so if anything in it fails it shouldn't bomb out the agent run. 
It does generate a lot of logs, which is partially by design, though I may make these concise and less verbose in the future. They look something like:
```
Running ingestion healthcheck validation!
Validating configuration...
Jira details:
URL: ... 
Username: ...
Password: **********
==> Testing Jira connection...
Authenticating to Jira API at test using the username and password secrets for test of company test
==> Getting Jira version...
Found Jira version as [version]
==> Getting Jira deployment type...
Response headers does not contain X-ANODEID! Customer is NOT running Jira Data Center.
==> Getting Jira permissions...
Found granted permissions as
==> Testing Jira user browsing …
```
=> [OJ-30981 Full_validate on every agent run

jf_agent/main.py, jf_agent/util.py, jf_agent/validation.py
Adds a step to upload the logfile via signed URL, along with healthcheck.json. 
This will add a healthcheck.json field in the output directory of the agent as well, but it will be the same one that we upload earlier in the healthcheck.
=> [OJ-31849] Uploading logs along with validation to aid debugging

jf_agent/main.py
When the agent fails and is rolled back, we lose the logfile that got us to that point, which is bad because it hides important context. This will run the send_data step after failure, but _without_ the .done file, so we still have the data but we won't use it to actually run anything.
=> [OJ-31880] Uploading logs on error state

jf_agent/main.py, rollback_on_fail.sh
A "dead man's switch" of sorts, to allow us to upload logs in the case of _any_ failure, at least, hopefully.
Basically:
- In rollback_on_fail.sh, if we find we've failed, we kick off `main.py` _again_ with the `-f` flag, indicating `from failure`
- This will execute a fun special mode that doesn't download, but just sets the output directory to whatever we find as the last directory in the outdir.
- There's a catch-22 here that I'm trying to patch wherein we don't actually get the logs from _this_ send-only run of the agent, but working on fixing that by adding the old logfile to the curr directory.
=> [OJ-31903] Upload on Failure or Timeout

jf_agent/main.py
We're seeing this cause extended runtimes due to excess GitHub calls, disabling until we can optimize.
=> [OJ-31925] Disabling healthcheck temporarily

jf_agent/config_file_reader.py, jf_agent/main.py, jf_agent/validation.py, tests/test_jira_download.py, tests/test_main.py, tests/utils.py
- Remove failure if Jira URL or credentials don't exist, as some companies use MI for Jira and agent for Git.
=> [OJ-32117] Cleanup get_ingest_config Function and Exceptions

jf_agent/config_file_reader.py, jf_agent/main.py, pdm.lock, pyproject.toml
Bump JF Ingest version and de-risk generating JF Ingest config. JF Ingest will be controlled by a separate agent only config flag on the Jellyfish side, so this release will be restricted to only clients that have the config flag enabled
=> OJ-32108-agent-side-changes-for-memory-foot-print-reduction

jf_agent/data_manifests/git/generator.py, jf_agent/main.py
Move Manifest generation warning logs to DEBUG, where it will appear only in the log file and not in stdout
=> OJ-32219-move-manifest-logs-to-debugs

pdm.lock, pyproject.toml
Bump `jf_ingest` version in Agent. This was tested locally with orthogonal-networks, and this functionality is still hidden behind a config flag
=> OJ-32232-bump-jf-ingest-version

jf_agent/__init__.py, jf_agent/agent_logging.py, jf_agent/config_file_reader.py, jf_agent/main.py, jf_agent/util.py
Add a log queue listener and handler to the logging config that will periodically post log messages to Jellyfish to reduce the latency in receiving agent logs.
=> OJ 32624 OJ-32625  add logging queue handler

example.yml
Occasionally folks forget to change this, so make the default value more reasonable.
=> [OJ-32833] Update `example.yml` Earliest Issue DT to 2023

jf_agent/main.py
Adjust logic to delete left over JF Ingest files when JF Ingest crashes and rolls back to not use JF Ingest
I tested this by incorrectly setting my GDPR_active flag to False in my config.yml, which recreates a specific problem one of our customers experienced
=> OJ-33445: fix roll back logic when jf ingest crashes

jf_agent/agent_logging.py
add logging to inform us when the logging config gets setup and torn down. Note that the second log in the `close_out` function: `Log stream stopped.` will not get picked up by the listener and sent to Jellyfish, as the listener is stopped before that statement is made.
=> log during logging setup and teardown

jf_agent/main.py, jf_agent/validation.py, pdm.lock, pyproject.toml
- always run Jira validation via jf_ingest when in a pull mode
- run git validation if asked for, but not yet through jf_ingest and only when in validate mode
- bump jf_ingest so we can dump the dataclasses safely to json
taking a look at the dev bucket I can see the healthcheck file was uploaded along with the other json files.
=> Oj 33568  upload health test results during full run

pdm.lock, pyproject.toml
Update dependencies for TQDM and JF Ingest, which we believe may be related to a strange string formatting error we're seeing for certain clients when they hit the BitbucketCloud RateLimiter
=> OJ-33810: update jf ingest and tqdm dependencies

example.yml, jf_agent/config_file_reader.py
Add in an OPTIONAL (opt in) configuration flag that allows you to skip saving JIRA files to the local disc. This is a helpful features for clients who have a large amount of Jira Issues they plan on ingesting, and they do not care about saving the files to their local disc. This feature is only available for customers using `jf_ingest` (which is almost all customers who are running off of latest). This change is made possible because `jf_ingest` uploads all jira data as soon as it's ready, instead of waiting until the end of the agent run to submit data.
To test I ran this code with `orthogonal-networks` data with and without the new flag. I verified that with and without the new flag data makes it to our S3 bucket, but WITH the new flag there is no jira data saved locally to disc.
=> OJ-34323-add-skip-saving-local-run-mode-for-jira

.github/workflows/endor.yml
This PR adds support for a new tool we want to use for software composition analysis (that will replace Snyk). This adds two modes:
1. A PR-time scanning mode which determines what changed relative to master. As of now this does not block PRs or even post comments. However, it provides the framework to do so in the future.
2. A monitor-style job that runs every time new content is pushed to master, which creates a bill-of-materials and sends to our Endor labs tenant that we can use to track dependencies and vulnerabilities.
Scans take around 2 minutes to complete, and run in parallel with other jobs, so merging this should be a non-issue.
=> [SECTEAM-905] Add support for endor as a SCA tool

jf_agent/main.py
Remove Manifests from Agent
Why?
Because Jira Manifests are already removed from Agent, and Git Manifests are still technically not prd ready. Generating manifests in Agent wastes our API read capacity for no reason
=> OJ-34538: remove manifests from agent

pdm.lock, pyproject.toml
This PR upgrades `jira` to 3.1.1 since:
1. `jf_ingest` supports that
2. `jellyfish` now runs `jira` 3.1.1
3. This is needed to eventually migrate auth to use solely Atlassian Connect
This should be a pretty safe change given it's already been verified in `jf_ingest` and has been running in `jellyfish` for over a day without any reported issues.
To test this, I ran the agent on orthog's JIRA and GitHub before and after the `jira` upgrade. The output of each is provided below. Notably, no notable differences exist between the two:
```
==> Testing Jira connection...
Authenticating to Jira API at https://jelly-ai.atlassian.net using the username and password secrets for josiah.bruner@jellyfish.co of company orthogonal-networks
==> Getting Jira version...
Found Jira version as …
```
=> [OJ-34993] Upgrade jira to 3.1.1

jf_agent/data_manifests/jira/adapter.py, jf_agent/jf_jira/jira_download.py, jf_agent/jf_jira/utils.py, pdm.lock, pyproject.toml
Include 502,503,504 errors in retry handling
=> [OJ-34978] Updates to jf_ingest For Better Retry Handling

pdm.lock, pyproject.toml
Bump Agent version to address problem with ingesting deleted worklogs
To test, I ran an agent ingest with orthog git and jira data
=> OJ-35036: bump agent version

jf_agent/jf_jira/jira_download.py
Fix exception: 
```
589   │ 2024-05-06 06:19:58,942 MainThread DEBUG jf_agent.jf_jira.jira_download Attempting wild card search with
590   │ 2024-05-06 06:19:58,942 MainThread ERROR jf_ingest.logging_helper [3002] Failed to download jira data:
591   │ Either 'user' or 'query' arguments must be specified.
592   │ 2024-05-06 06:19:58,944 MainThread ERROR jf_ingest.logging_helper Traceback (most recent call last):
593   │   File "/home/jf_agent/jf_agent/jf_jira/__init__.py", line 141, in load_and_dump_jira
594   │     download_users(
595   │   File "/python/pkgs/jf_ingest/diagnostics.py", line 66, in wrapper
596   │     ret = func(*args, **kwargs)
597   │   File "/python/pkgs/jf_ingest/logging_helper.py", line 28, in wrapper
598   │     ret = func(*args, **kwargs)
599   │   File …
```
=> [OJ-35134] bugfix: `jira` version 3.1.1 validates `search_users` params

example.yml, jf_agent/config_file_reader.py, pdm.lock, pyproject.toml
Do a big JF Ingest version bump to allow us to use the new `recursively_download_parents` field, which an Agent Client has expressed interest in. This flag WILL NOT run for anyone unless they explicitly set it in their `config.yml`
=> OJ-35552: committing agent changes to allow for parent deep pull

jf_agent/__init__.py, jf_agent/agent_logging.py, jf_agent/data_manifests/git/generator.py, jf_agent/data_manifests/jira/adapter.py, jf_agent/git/github.py, jf_agent/git/github_gql_adapter.py, jf_agent/jf_jira/__init__.py, jf_agent/jf_jira/jira_download.py, jf_agent/main.py, pdm.lock, pyproject.toml
Improve how we divert/filter what logs go to the Console logger and what logs go to the Agent Log file.
Previously, we relied on exclusively filtering DEBUG level messages away from the Console logger, but into the Log file Handler. Now, we rely on the `send_to_agent_log_file` helper function from `jf_ingest.logging_helper`, which explicitly tags log records as being for only the agent log file. This allows us to retain the log records levels, instead of flattening them all to `logging.DEBUG`
This PR must be merged after [this ingest PR is merged and deployed](https://github.com/Jellyfish-AI/jf_ingest/pull/120)
Here is the Agent Console output, which is very user friendly. Below that is the log file, which contains some extra logging information (NOTE: the logs around "skipping sprints" …
=> OJ-35758: rework log handlers to use a smart filter

jf_agent/main.py
There is a latent bug in the diagnostics monitoring thread. The logic flow to shut down the monitoring thread requires us to be in a mode where we are downloading/sending data. If the Agent is run in a `send_only` mode or `from_failure` mode, it will fail to close down the diagnostics thread and hang forever (well, technically it will get shutdown after 72 hours due to some time out logic we have in the Agent)
To resolve this issue, I moved the `diagnostics` cleanup logic (where we shut down the thread) to be part of a `try/finally` logic block so that it always gets run for ever run mode and even if we encounter an error
=> OJ-36885: always close down diagnostics file and thread

jf_agent/config_file_reader.py, jf_agent/git/__init__.py, jf_agent/git/utils.py, jf_agent/main.py, jf_agent/validation.py, pdm.lock, pyproject.toml
Set up JF Ingest Github GQL for all companies that are already running the original Agent version of the GQL ingest. I tested this with orthogonal-networks in an "end to end" test; I ran an Agent run for our git instance, imported it to `stg-looking-glass` via `git_import`, and then ran the Agent again. I verified that the first Agent run and submission created a few PRs and commits and branches, and then verified that the second run didn't create anything new. 
This PR contains initial groundwork that will be helpful as we roll out ADO in the Agent (via `jf_ingest`)
=> OJ-36861-setup-jf-ingest-for-github

.gitignore, jf_agent/config_file_reader.py, jf_agent/git/__init__.py, jf_agent/git/utils.py, jf_agent/main.py, pdm.lock, pyproject.toml
Introduce the ADO adapter to Agent.
A lot of this seems to be `isort` and `black`?
The bulk of this logic is to allow somebody to provide an ADO config/creds combo and run the Agent. [To see my proof of testing](https://github.com/Jellyfish-AI/jellyfish/pull/24558), see this PR (which is in Jellyfish, to protect a customer name)
To test backwards compatibility, I ran the Agent for orthog for both Jira and Git. Additionally I did more testing for a specific customer, [but I am keeping that testing plan in this private PR](https://github.com/Jellyfish-AI/jellyfish/pull/24558) for customer privacy concerns.
```
Logging setup complete with handlers for log file, stdout, and streaming.
Will write output files into ./output/20240805_175013
Running ingestion healthcheck validation!
Validating …
```
=> OJ-36874: introduce ado adapter to agent

jf_agent/main.py
Adds a try/except around request to Jellyfish API when attempting to retrieve company slug
=> OJ-37554 - Add try/except around request

jf_agent/agent_logging.py, jf_agent/main.py, jf_agent/util.py
In the agent we do a pretty good job with structured logging, but there isn't a quick way to tell via Log Insights if an agent run was successful or not. To fix this, I made some small adjustments to our logging in the Agent
1. I added a clearer "Starting Agent Run..." DEBUG log message, which will show up in log insights
2. I added an `commit_is_latest` tag in the structured logging, so that you can tell if the customer is running the latest Agent SHA or not
3. On the `Done!` log message, I added some structured logs associated with it that will show the status of each individual Agent task we tried to run. This will make it easier to search and monitor via Log Insights if we shipped a breaking change
=> Oj 39015 add in status debug log

pdm.lock, pyproject.toml
Version bump to fix ADO bug that had to do with referencing a variable before it was instantiated (v0.0.137). Includes bump that deals with small Custom Fields bug as well (v0.0.136)
Ran this with orthogonal-networks for Jira and Git
=> OJ-39254: version bump to fix ado bug

jf_agent/agent_logging.py
There is some faulty error handling when submitting logs to Jellyfish. We have a `try`/`except` block around our `con.request` call, but we do not have the `conn.getresponse()` logic wrapped in the `try` block. It is possible to raise errors here (connection already closed). This is bad. We NEVER want to fail because we fail to upload logs via the log stream. We want the agent to finish, because when it does finish we can get the full log file, as well as any data we churned through
This is a small low risk change, and I'm not sure how to specifically recreate it locally. I ran the agent against orthog as a smoke test, though
=> OJ-39279: fix error handling when submitting logs to JF

jf_agent/jf_jira/jira_download.py, pdm.lock, pyproject.toml
This uses the `mark_for_redownload` kwarg in `identify_custom_field_mismatches` to send mismatched custom field issues to Jellyfish to redownload them.
=> OJ-39182 Mark custom field issue mismatches for redownload

jf_agent/config_file_reader.py, jf_agent/git/utils.py, jf_agent/main.py
There is a bug that occurs when uploading git data via JF Ingest. JF Ingest uploads data as it gets it, this is good and intentional. At the end of the agent processing we then check if we need to upload any additional data. There is a bug where do not detect the already uploaded git data properly, and we upload it twice
I tested this with orthog git uploading and verified that we do not upload twice
Old upload pattern (bad 😢)
New upload pattern (good 😄)
=> OJ-39228: fix double uploading bug in git data

pdm.lock, pyproject.toml
Bump Agent Version. This will include a fix to the ADO adapter that will correct a bug in JF Ingest that is causing a major slow down for large customers.
Using a direct connect customers authentication, I was able to verify that the ADO bug no longer happens in this Agent Version. With this change, we downloaded 900 PRs. Without this change, we are downloading 6,000+ PRs
Additionally, I used our internal customer (orthogonal-networks) to verify that github connections and Jira Still works
=> OJ-40042: Agent Version bump

jf_agent/main.py
This change updates the logic for pulling Jira issue metadata from Jellyfish. This ensures customers with larger data sets aren't experiencing timeouts from substantial responses from the Jellyfish API endpoint for `agent/pull-state`.
This change cannot be merged until https://github.com/Jellyfish-AI/jellyfish/pull/26290 is deployed.
Tested locally (replaced values with `x`):
```
    ~/c/jf_agent     OJ-40908-pagination-jid !1  pdm run jf_agent/main.py -e ./creds.env --jellyfish-api-base http://localhost:8000
2024-12-20 19:00:52 [info    ] Logging setup complete with handlers for log file, stdout, and streaming.
2024-12-20 19:00:55 [info    ] Pulling additional Jira issue metadata from Jellyfish...
2024-12-20 19:01:02 [info    ] Pulled x additional Jira issue metadata in x …
```
=> [OJ-40908] Use cursor based pagination for Jira issue metadata

jf_agent/exception.py, jf_agent/main.py
Add verbose logging when pulling additional Jira issue metadata from the Jellyfish cursor-based pagination endpoint. Also, enhance the logging when a `BadConfigException` is raised.
Tested locally (some numerical values replaced with `x`):
```
2024-12-24 19:53:10 [info    ] Logging setup complete with handlers for log file, stdout, and streaming.
2024-12-24 19:53:14 [info    ] Pulling additional Jira issue metadata from Jellyfish...
2024-12-24 19:53:14 [info    ] Pulling Jira issue metadata with cursor x (request 0)...
2024-12-24 19:53:16 [info    ] Request 1 took 2.09s
2024-12-24 19:53:17 [info    ] Pulled x Jira issue metadata so far in 1 requests and 2.13s.
2024-12-24 19:53:17 [info    ] Pulling Jira issue metadata with cursor x (request 1)...
2024-12-24 19:53:18 [info    ] Request 2 …
```
=> [OJ-40908] Verbose Jira issue metadata logging

jf_agent/main.py
This PR consists of two functional changes with how Jira issue metadata is pulled from Jellyfish:
1. When pulling issue metadata from Jellyfish, we actually pull two copies of it - one in a `dict` format and one in an object-to-json string format. This PR adds a param to the request made to JF so that only the `dict` formatted issue metadata is required. The required string formatted data is then recreated using the one copy of the data we pull. This greatly reduces the size of the initial `pull-state` request made to JF. This functionality is dependent on https://github.com/Jellyfish-AI/jellyfish/pull/26328.
2. While pulling issue metadata using the cursor-based pagination endpoint, the initial limit is set to the max results allowed from the endpoint (25k). On failures, we'll halve the …
=> [OJ-40908] Issue metadata improvements

jf_agent/agent_logging.py
Before adding the logging handler/listener for outbound logs sent to the JF endpoint to our logging setup, check if we can reach that endpoint successfully. If not, do not add the streaming logging config to our logging setup.
Tested locally:
```
2024-12-27 16:27:33 [info    ] Connection failed to JF streaming logs endpoint - Not streaming logs to Jellyfish.
2024-12-27 16:27:33 [info    ] Logging setup complete with handlers for log file, console.
...
```
=> [OJ-40122] - Test connection for outbound logs

jf_agent/agent_logging.py, jf_agent/main.py
Only try to send agent diagnostic data to the JF webhooks endpoint if the earlier test to send logs to the same domain was successful
=> [OJ-40908] Only send diagnostic data if JF webhooks endpoint is reachable

jf_agent/git/gitlab_client.py
This updates our `.list()` calls that were previously passing `as_list=False` to get a generator back to instead pass `iterator=True`. This was a breaking change introduced with newer versions of the GitLab dependency used to call the API.
=> OJ-41290 Update GitLab list pulls to use iterator keyword

pdm.lock, pyproject.toml
Version bump to fix a small regression for a subset of our clients using the `include_fields` and `exclude_fields` parameter
Verified fix with a local orthogonal-networks run
=> OJ-41753: version bump for include fields fix

jf_agent/config_file_reader.py
This should now support generating the auth config for GitLab when using the ingest adapter.
=> OJ-42967 Add missing auth config creation for GitLab Ingest

pdm.lock, pyproject.toml
This brings the new ingest adapter in line with how we handle org misses when we are not performing discovery.
=> OJ-43854 Allow ingest GitLab adapter to skip unavailable orgs

pdm.lock, pyproject.toml
- Add support for skipping ssl verification. [OJ-44311]
- Check against id for included repositories. [OJ-44238]
- Allow fallback to /version if /metadata is unavailable. [OJ-44267]
- Properly log/raise auth error if certain status codes returned when fetching an org. [OJ-43322]
[OJ-44311]: https://jelly-ai.atlassian.net/browse/OJ-44311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-44238]: https://jelly-ai.atlassian.net/browse/OJ-44238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-44267]: https://jelly-ai.atlassian.net/browse/OJ-44267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-43322]: …
=> [OJ-44311] (+3 more) Fixes for GitLab

pdm.lock, pyproject.toml
This includes a fix that looks at a given GitAuthConfig to determine ssl verification and a change in our inclusion/exclusion logic to include either the project name *or* id regardless of provider.
=> OJ-44238 OJ-44311 Fix Gitlab ingest ssl verification and inclusion/exclusion of projects

pdm.lock
This PR updates several transitive dependencies (virtualenv, cryptography, setuptools, and certifi) to address many CVEs known to affect these packages.
Most of these are pretty low risk changes (setuptools and virtualenv, most notably). `cryptography` is fairly stable with respect to interface changes, so assuming the agent runs and behaves as expected in a few environments, I'm pretty confident about that change.
Perhaps the most interesting is the `certifi` change. Whole the upgrade itself seems pretty benign (cert lists change all the time) this upgrade is notable in that it removes the GLOBALTRUST root cert following contention and removal from Mozilla's trust list. This shouldn't much matter but it's possible some customers could be affected if they happened to have internal server …
=> [OJ-44510] Update dependencies to address several CVEs

example.yml, jf_agent/config_file_reader.py, pdm.lock, pyproject.toml
Version bump JF Ingest to add some new configuration options
- Add `filter_boards_by_projects` which will allow customers to leverage the `projectKeyOrId` parameter on the Jira API. When provided we will only query for boards related to the projects they want to include. **This is not, and should not, be the default behavior.** Many times customers want to ingest "user" boards, which aren't associated with any projects. This flag is only for customers who don't care much about boards, have too many boards to consume, or who want to speed up their initial ingestion by pulling in the minimum amount of boards possible
- Expose the `keep_base_url` flag for gitlab customers. When provided and set to `True` we will use the `keep_base_url` argument provided by the Gitlab Python module. This can …
=> OJ-45053: bump version and change config

.github/workflows/pr-checks.yml, jf_agent/validation.py, pdm.lock, pyproject.toml
When measuring the size of the output dir after an Agent Run we rely on the `config` object to get the local working directory. If a malicious actor messed with the `config` they could technically make the agent container vulnerable to a command injection attack. The `config` object is maintained by the user that creates/operates the Agent Container so the risk of this is incredibly low. One of our customers, however, is reporting that their security scanning tools are flagging this. In order to improve the data security of the Agent we are making this change to better protect against commend injection attacks.
**Note:** this code path is only accessible when running the Agent in `validate` mode, which is generally only used as a debugging step
=> OJ-45476: refactor how we get output dir size

.sonar-project.properties
These are test values and do not drive anything important. SonarQube will only pick up properties if included in the `.sonar-project.properties` file at the root level on the main branch. In addition to adding properties, there are a number of settings and scopes available for this configuration file. There are additional properties and values that can be set via CD/CI via `sonar-project.properties`, not included in this PR.
=> Add sonarqube properties file for analysis values in webhooks
