Jellyfish-AI/jf_agent

- .flake8
- .gitignore
- Pipfile
- jf_agent/bb_download.py
- jf_agent/jira_download.py
- jf_agent/main.py
- setup.py
Adds support for downloading users, projects, repositories, branches, commits, and pull requests for on-premise Bitbucket servers.
> Support for Bitbucket Server downloading

- jf_agent/jira_download.py
Handle
- Fields identified by 'id', not 'key'
- Boards that are global, not tied to projects
- Boards that are private to a user
> Support for Jira Server 6 and 7:

- jf_agent/bb_download.py
- jf_agent/jira_download.py
- jf_agent/main.py
- pyproject.toml
> handle empty repo

- jf_agent/bb_download.py
- jf_agent/main.py
Retry on authentication and connection failures by intercepting requests made from stashy module.
> Retry on Connection and Authentication Failures

- jf_agent/bb_download.py
- jf_agent/main.py
Replaced session request retry subclass with urlllib.Retry class
> Use urllib Retry Module for BBC session

- .gitignore
- jf_agent/jira_download.py
- jf_agent/main.py
Should be pretty straight-forward. 
Tested for orthogonal-networks. 
Not sure if I can test our actual agent customers or if we simply don't have the creds.
> [OJ-5239]: Support for custom field options

- jf_agent/github_client.py
> skip repos that result in a 403 when we try to fetch them

- jf_agent/diagnostics.py
Add newlines to diagnostics file to facilitate parsing.
> [OJ-5741]: Add newlines to diagnostics file

- jf_agent/jira_download.py
- jf_agent/main.py
**Purpose**:
**Jira Ticket**: https://jelly-ai.atlassian.net/browse/OJ-5774
**Component JSON**:
```
[
{
"expand": "description,lead,issueTypes,url,projectKeys,permissions,insight",
"self": "https://jelly-ai.atlassian.net/rest/api/2/project/10000",
"id": "10000",
"key": "OJ",
"name": "Original Jellyfish",
"avatarUrls": {
"48x48": "https://jelly-ai.atlassian.net/secure/projectavatar?pid=10000&avatarId=10400",
"24x24": "https://jelly-ai.atlassian.net/secure/projectavatar?size=small&s=small&pid=10000&avatarId=10400",
"16x16": "https://jelly-ai.atlassian.net/secure/projectavatar?size=xsmall&s=xsmall&pid=10000&avatarId=10400",
"32x32": "https://jelly-ai.atlassian.net/secure/projectavatar?size=medium&s=medium&pid=10000&avatarId=10400"
},
"projectCategory": {
"self": …
```
> OJ 5774 - Ingest Jira Components

- jf_agent/git/github.py
Github integration broken due to using the wrong github_client function names. Fixed this, and added typing to client parameters in order to get warnings in future.
> OJ-6236: GitHub Bugfix

- jf_agent/jf_jira/jira_download.py
Reverts Jellyfish-AI/jf_agent#72
> Revert "OJ-6895"

- README.md
- jf_agent/main.py
* Document required Jira Field list in the README
* Warn if required fields are excluded in the configuration
> OJ-7389: Document required Jira Fields

- jf_agent/git/gitlab_adapter.py
We suspect tight permissions set on the repo level may raise 404s during the initial download.. skip and log for now, and allow the download to continue running on the good repos
> OJ-8644: Skip and log gitlab 404s

- README.md
- jf_agent/__init__.py
- jf_agent/config_file_reader.py
- jf_agent/diagnostics.py
- jf_agent/jf_jira/__init__.py
- jf_agent/jf_jira/jira_download.py
- jf_agent/main.py
- Add a new `validate` mode that will test basic Jira connectivity
- Add some additional github enterprise validation
- be louder if there are no jira users found
> [OJ-8356] [OJ-8365] More diagnostics

- jf_agent/config_file_reader.py
- jf_agent/git/__init__.py
- jf_agent/git/bitbucket_cloud_client.py
- jf_agent/git/gitlab_adapter.py
- jf_agent/git/gitlab_client.py
- jf_agent/jf_jira/jira_download.py
- jf_agent/main.py
Capture the "system" property of a GitLab PR note (comment)
> OJ-9346: GitLab PR comments

- example.yml
- jf_agent/config_file_reader.py
- jf_agent/git/bitbucket_server.py
Adds some verbose logging (off by default, enabled via config.yml when desired) to Bitbucket Server. New logging is all client-side (not sent).
> OJ-9902 verbose

- jf_agent/git/bitbucket_server.py
It seems that some PRs will throw a `ChunkedEncodingError` consistently when we try and fetch them from Bitbucket Server. This seems like a bug in Bitbucket Server's handling of binary files, so if we see it just print a debug error message and move on.
> [OJ-10195] Skip PRs that throw `ChunkedEncodingError` from Bitbucket Server

- jf_agent/jf_jira/jira_download.py
Expand criteria for falling back to search by user name to approximately 1000.
> [OJ-10596]: User search more flexible

- jf_agent/main.py
Currently, the agent’s “validate” mode checks that the agent can contact Jira, that it can enumerate Jira users, and that it has access to the Jira projects it’s configured for. This PR adds the following functionality:
- Show how much RAM is available in the context it’s running in
- Show how much disk space is available on the output directory (`/home/jf_agent/output`)
Local agent "validate" mode runs
Agent output available upon request
> OJ-10525: Include disk space and memory statistics in agent validation

- jf_agent/config_file_reader.py
- jf_agent/main.py
Return an exit code of 1 to indicate agent failure if something goes wrong during a run
> [OJ-10536] Return non-zero exit code if something goes wrong

- example.yml
- jf_agent/config_file_reader.py
- jf_agent/git/__init__.py
- jf_agent/git/github.py
- jf_agent/main.py
This reverts commit e272e068f9dc0ee3c72c7a106ecf64f1d6ae5230.
> Revert "OJ-11220: Add support for specifying commit branches for github (#143)"

- Pipfile
- Pipfile.lock
> bump urllib3 to 1.26.5 or higher

- docs/_setups/jira-setup.md
…epending on Jira type
Testing - Ran jekyll serve locally and checked out the change
> Oj 12941 toekn auth doc

- example.yml
- jf_agent/config_file_reader.py
- jf_agent/git/gitlab_adapter.py
See https://github.com/Jellyfish-AI/jf_agent/pull/169 and https://github.com/Jellyfish-AI/jf_agent/pull/170
A couple of additional minor tweaks made, as per the comments on [#169](https://github.com/Jellyfish-AI/jf_agent/pull/169)
> OJ-14303-14305: GitLab include exclude by parents

- Dockerfile
What it says on the tin - remove an unused dependency from our Dockerfile
> Remove Unused Dependency

- jf_agent/git/github_client.py
I was running some tests and I couldn't download any data from GitHub; I would get this in the console output (`<USER ID>` has been used to protect the innocent):
```
Obtained github configuration, attempting download...
downloading github users... [3061] Failed to download github data:
404 Client Error: Not Found for url: https://api.github.com/users/<USER ID>
Traceback (most recent call last):
File "/home/jf_agent/jf_agent/git/__init__.py", line 312, in load_and_dump_git
load_and_dump_gh(
File "/home/jf_agent/jf_agent/diagnostics.py", line 42, in wrapper
ret = func(*args, **kwargs)
File "/home/jf_agent/jf_agent/agent_logging.py", line 44, in wrapper
ret = func(*args, **kwargs)
File "/home/jf_agent/jf_agent/git/github.py", line 40, in load_and_dump
outdir, 'bb_users', …
```
> fix: skip missing or broken GitHub users

- jf_agent/jf_jira/jira_download.py
A customer is having a problem of the GET url being too long.
This ticket will chuck on the project_ids if they are too long.
Tested locally with ortho.
Jira Ticket:
https://jelly-ai.atlassian.net/browse/OJ-18051
> OJ-18051: Chunk up long project_ids for GET request

- jf_agent/agent_logging.py
- jf_agent/main.py
Improve logging to the agent uploading logic to ensure that all logs, and possible exceptions, are captured.
> OJ-21219-better-logging-in-agent-submission

- jf_agent/main.py
Remove Exception for unique tokens. This was not a hard requirement - more of a friendly suggestion.
> Remove BadConfigException for duplicate token use

- Pipfile
- Pipfile.lock
- jf_agent/agent_logging.py
- jf_agent/jf_jira/jira_download.py
- tests/test_data/jira/test_issues_response.json
- tests/test_jira_download.py
> OJ-22511, OJ-22619: skip issue on 500

- jf_agent/data_manifests/jira/adapter.py
- jf_agent/data_manifests/jira/generator.py
- jf_agent/data_manifests/jira/manifest.py
> OJ-25733-update-agent-manifests-to-include-project-keys

- jf_agent/agent_logging.py
- jf_agent/jf_jira/jira_download.py
- tests/test_jira_download.py
Little awkward since jira seems to not tell you when you've reached the end of sprints, just returns an empty list, so we have this "here's an empty list, try again" dance until a "here's an empty list and don't try again because it went correct, just empty"
> OJ-26479: same deal as the 500 skip, same test structure

- jf_agent/agent_logging.py
- jf_agent/jf_jira/jira_download.py
- tests/test_jira_download.py
Reverts Jellyfish-AI/jf_agent#230
> Revert "OJ-26479: same deal as the 500 skip, same test structure"

- jf_agent/main.py
Report success/failure _before_ sending logs to S3.
> [OJ-26896] Report Agent Success/Failure In Logs

- jf_agent/data_manifests/git/generator.py
- jf_agent/data_manifests/jira/adapter.py
- jf_agent/main.py
Make manifest logging less scary
> OJ-26470-reducing-manifest-log-severity

- jf_agent/data_manifests/git/adapters/github.py
- jf_agent/data_manifests/git/generator.py
- jf_agent/git/github_gql_client.py
Deduplicate some shared logic and consolidate all Github Graphql calls to one file
> OJ-28328-cleanup-graphql-duplicated-client-logic

- jf_agent/git/github_gql_client.py
Add in logic to better handle when a PR author is a Bot. Before, we were fragmenting on only the `User` GQL object. Now, we fragment on both `User` and `Bot`, to insure that we grab the Bot's ID if we are dealing with a Bot instead of a user
This new fragmentaiton logic has been copied around to everywhere that GQL references an Actor object
Updated documentation to reflect some of these gotchas
> OJ-28537-improve-fragmentation-when-processing-gql-actor-objects

- jf_agent/git/github_gql_client.py
The Github API seems to give us back some untrustworthy values for it's `retry-after` header. Add in some logic to better guard against bogus values
I tested this by making a bunch of threads to call/throttle our API. The throttler was hit and successfully handled
```
iter:  115
A secondary rate limit was hit. Sleeping for 63 seconds. (attempt 1/7)
A secondary rate limit was hit. Sleeping for 63 seconds. (attempt 1/7)
A secondary rate limit was hit. Sleeping for 63 seconds. (attempt 1/7)
A secondary rate limit was hit. Sleeping for 63 seconds. (attempt 1/7)
A secondary rate limit was hit. Sleeping for 63 seconds. (attempt 1/7)
A secondary rate limit was hit. Sleeping for 63 seconds. (attempt 1/7)
A secondary rate limit was hit. Sleeping for 63 seconds. (attempt 1/7)
A secondary rate limit …
```
> OJ-28623: fix negative sleep time bug when doing rate limit handling

- jf_agent/main.py
- jf_agent/validation.py
pack bins of git configs with projects according to number of repos per project
> OJ-28598: packing/shuffling

- jf_agent/main.py
- jf_agent/validation.py
Reverts Jellyfish-AI/jf_agent#255
> Revert "OJ-28598: packing/shuffling"

- .secrets.baseline
- pdm.lock
- pyproject.toml
- tests/test_jira_download.py
Add in the `pytest` library to PDM. Also clean up a few problems detected when testing
> OJ-28807-at-py-test-via-pdm

- jf_agent/jf_jira/jira_download.py
Reverts Jellyfish-AI/jf_agent#265
> Revert "OJ-28853: get around 2500 character limit when querying"

- jf_agent/agent_logging.py
- jf_agent/data_manifests/jira/adapter.py
- jf_agent/jf_jira/jira_download.py
- jf_agent/jf_jira/utils.py
- jf_agent/validation.py
Retry for Jira rate-limiting in all places we query Jira.
> [OJ-29537] Gracefully Retry for Jira Rate-Limit Errors

- Dockerfile
- rollback_on_fail.sh
> OJ-28905 part 2: agent rollback 

- jf_agent/jf_jira/jira_download.py
Fix some bad batching logic when fetching a large amount of Jira issues. In a function that batches pages, we were returning with a `return` statement instead of using a yield statement.
To Test this I spoofed our functions to pull a years worth of orthogonal-networks data, along with some logic changes to make our batches MUCH smaller to throttle the batching logic. I was able to fetch all issue data with the 'server safety' throttle batching things in groups of 7
> OJ-30360-fix-page-batching-bad-logic

- jf_agent/jf_jira/__init__.py
Upload info on metadata to see what kind of metadata we're getting on issues.
> [OJ-31757] Debugging Info

- jf_agent/config_file_reader.py
- jf_agent/main.py
- pdm.lock
- pyproject.toml
This is the agent side changes to allow JF Inges to be used, if the feature flag is set
> OJ-29730-jf-ingest-agent-side-changes

- jf_agent/data_manifests/jira/adapter.py
- jf_agent/jf_jira/__init__.py
- jf_agent/jf_jira/jira_download.py
not when hitting a specific endpoint
> rewrite session header accept when making connection

- jf_agent/main.py
Previously, before JF Ingest, if JIRA failed it would be a 'soft' failure and move on to attempt to download GIT data as well as upload logging and diagnostic information. With the rollout of JF Ingest, however, a bug was introduced that made JIRA failures a hard failure. This PR seeks to address that and make the JIRA failure soft again
> OJ-32077-make-jira-fail-a-soft-fail

- jf_agent/agent_logging.py
Try and remove the race condition where we are attempting to create the log stream more than once. This is technically redundant since the log endpoint will be resilient against attempts to create a duplicate log source
> better logic around creating the log stream

- jf_agent/config_file_reader.py
- pdm.lock
- pyproject.toml
Upgrade the JF Ingest version and make a small change to config generation so that we can release JF Ingest for all customers
> OJ-33313-jf-ingest-release-for-agent

- jf_agent/jf_jira/jira_download.py
- jf_agent/ratelimit.py
There is a bad logging call deep in the BBCloud rate limiter logic that rarely gets hit. One of our clients, however, has hit it and failed their git agent upload on it.
> OJ-33816: fix bad logging call in agent

- pdm.lock
- pyproject.toml
Bump JF Ingest version to improve error logging
> OJ-33908: bump ingest version to improve agent logging

- pdm.lock
- pyproject.toml
> [OJ-36478] Respect Include/Exclude Project Categories for Diagnostics, ingest bump

- rollback_on_fail.sh
Remove agent rollback logic - unstable.
> [OJ-36936] Remove Agent Rollback Logic

- pdm.lock
- pyproject.toml
Adds a dependency for the `structlog` package to pdm. Also updates the lock strategy used by pdm.
> Structlog dependency

- jf_agent/config_file_reader.py
- jf_agent/git/utils.py
- jf_agent/main.py
Fixes regression introduced in 9d4908121f5fee783546b14187bfe417a9507172; should only generate an ingestion config for supported jf_ingest providers.
> [OJ-37210] Remedies Regression Affecting GitLab Customers (And Likely BBC/BBS)

- .github/workflows/endor.yml
- example.yml
Update agent config example to include ADO references
> OJ-38433: update agent documentation for example config

- example.yml
I've been working with our internal documentation team to clean up the help center docs. Along side those changes, we'd like to change the `example.yml` file to also be as up to date and helpful as possible
> OJ-38549: update example yml file

- pdm.lock
- pyproject.toml
Bumping version of jf_ingest to incorporate this fix: https://github.com/Jellyfish-AI/jf_ingest/pull/184
> [OJ-39027] Bump jf_ingest version

- pdm.lock
- pyproject.toml
Update jf_ingest to latest version
> OJ-40275 - Update jf_ingest

- pdm.lock
- pyproject.toml
Bump jf_ingest to v0.0.157
Ran agent locally to test
```
2024-12-18 17:25:22 [info    ] Logging setup complete with handlers for log file, stdout, and streaming.
2024-12-18 17:25:42 [info    ] Will write output files into ./output/20241218_172522
2024-12-18 17:25:42 [info    ] Running ingestion healthcheck validation!
2024-12-18 17:25:43 [info    ] Running Jira Download...
2024-12-18 17:25:43 [info    ] Authenticating to Jira API at https://jelly-ai.atlassian.net using the username and password secrets for eric.lheureux@jellyfish.co of company orthogonal-networks
2024-12-18 17:25:44 [info    ] Authenticating to Jira API at https://jelly-ai.atlassian.net using the username and password secrets for eric.lheureux@jellyfish.co of company orthogonal-networks
2024-12-18 17:25:44 [info    ] …
```
> [OJ-40779] Bump jf_ingest

- jf_agent/config_file_reader.py
- pdm.lock
- pyproject.toml
Add JQL filter to config object passed to `jf_ingest` and bump `jf_ingest` version
> [OJ-41016] JQL filter

- jf_agent/agent_logging.py
Set timeout for streamed logging requests and update logging config
> [OJ-40908] Update logging config

- jf_agent/main.py
- pdm.lock
- pyproject.toml
Bump jf_ingest version and utilize param to optionally send diagnostic data
> [OJ-40908] Bump jf_ingest

- jf_agent/agent_logging.py
Small update to:
- Update unsuccessful streaming log message to clearly state that the agent run can proceed without issue
- Better type hinting
> [OJ-41072] Log messages

- pdm.lock
- pyproject.toml
Version Bump, includes changes to better scrub changelogs when ingesting Jira Issues
> OJ-41520: version bump

- pdm.lock
- pyproject.toml
Version bump for filter changelogs fix
> OJ-41685: version bump

- pdm.lock
- pyproject.toml
Version bump to fix bug related to not pulling all users on some jira server versions, related to this Jira Server bug: https://jira.atlassian.com/browse/JRASERVER-65089
> OJ-42327: agent version bump

- .github/workflows/pr-checks.yml
- jf_agent/config_file_reader.py
- jf_agent/git/__init__.py
- jf_agent/main.py
- pdm.lock
- pyproject.toml
Adds support for using the JF Ingest adapter for GitLab. Includes an ingest version bump.
> OJ-42967 Support JF Ingest Gitlab adapter

- pdm.lock
- pyproject.toml
Bump jf_ingest to include conditional check for GHE vs GHC for GQL actor fragment
> [OJ-45876] Bump jf_ingest version

- pdm.lock
- pyproject.toml
Bump jf_ingest version to add network exceptions to retry on
> [OJ-47790] Bump jf_ingest version

- pdm.lock
- pyproject.toml
JF Ingest bump to include fix for ChunkedEncodingError exceptions for GitLab
> Fix ChunkedEncodingError exception for Gitlab
